# @host = http://localhost:9999
@host = https://backend-09-server.herokuapp.comnpm

###
GET {{host}}/posts

###
GET {{host}}/posts/8

###

GET  {{host}}/posts/seenPosts/10

# ###

POST {{host}}/posts
Content-Type: application/json

{
    "id": 0,
    "content": "New Post",
    "type": "regular"
}

###

POST {{host}}/posts
Content-Type: application/json

{
    "id": 1,
    "content": "Updated Post",
    "type": "video"
}

###

DELETE {{host}}/posts/1

###

POST {{host}}/posts/2/likes

###

DELETE {{host}}/posts/1/likes